# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.
"""

import os
import subprocess
import shutil

def install():
  x=subprocess.run(["pip", "install", "mhcflurry"],
    encoding="utf-8", capture_output=True)
  y=subprocess.run(["mhcflurry-downloads", "fetch"],
    encoding="utf-8", capture_output=True)
  os.makedirs("input", exist_ok=True)
  return x

def test():
  with open('inputs.txt', 'w') as f:
    f.write('''allele,peptide
HLA-B*5801,AAAAAAAAA
HLA-B*5801,CCCCCCCCC
HLA-C*0702,DDDDDDDDD''')
  os.system("mv inputs.txt inputs.csv") #el base
  return subprocess.run("(mhcflurry-predict inputs.csv --out outputs.csv)",
      encoding="utf-8", capture_output=True, text=True,shell=True)

def run(dir_string=None, convert=True):
  if not dir_string:
    with os.scandir("input") as inputs:
      for input_sing in inputs:
        if os.path.isfile(input_sing) == True:
          input_sing = os.path.basename(input_sing)
          if input_sing.endswith(".csv"):
            dir_string = "input/" + input_sing
  if not dir_string:
    with os.scandir(".") as inputs:
      for input_sing in inputs:
        if os.path.isfile(input_sing) == True:
          input_sing = os.path.basename(input_sing)
          if input_sing.endswith(".csv"):
            dir_string = input_sing
  if not dir_string: #if it didnt find anything for some reason
    raise FileException("Error: no file found. (Does it have a wrong extension or is it placed on the incorrect folder?)")
  
  output = dir_string[:-4]
  #converting from a set structure#########################################
  import pandas as pd
  if convert:
    print("Converting CSV")
    filedirpath = os.path.dirname(dir_string)
    os.makedirs(f"backup/{filedirpath}", exist_ok=True)
    shutil.copyfile(dir_string, f"backup/{dir_string}")
    df = pd.read_csv(dir_string)
    #dfbkup = df
    df_headers = list(df.columns)
    mhcflurry_headers = ['allele','peptide']
    #specific MHCFLURRY Sorting

    #extra_df_headers = df_headers[2:] #extra is for future merging of csvs once I figure out how to use the output
    #extra_df = df.iloc[:, 2:]
    #annotation_df = df.iloc[:, 0]
    
    df = df.iloc[:, 1:3]
    df.columns = ['peptide','allele']
    df = df.reindex(columns=mhcflurry_headers)
    with open(dir_string, 'w') as outfile:
      outfile.write(df.to_csv(index=False))
      outfile.close()
  ###################################################################
  print("Processing")
  result = subprocess.run(f"(mhcflurry-predict {dir_string} --out {output}_MHC_results.csv)",
      encoding="utf-8", capture_output=True, text=True,shell=True)
  print("Success! Downloading your CSV shortly...")
  if convert:
    shutil.copyfile(f"backup/{dir_string}", dir_string)

  #merge result with original df
  dfresult = pd.read_csv(f"{output}_MHC_results.csv")
  dfconcat = pd.concat([pd.read_csv(dir_string), dfresult.iloc[:, 2:]], axis="columns")
  with open(f"{output}_MHC_results.csv", 'w') as outfile:
      outfile.write(dfconcat.to_csv())
      outfile.close()
  from google.colab import files
  files.download(f"{output}_MHC_results.csv")
  print(f"Downloaded on your local computer. Name: \"{dir_string[:-4]}_MHC_results.csv\"")
  return result
  #results_df = pd.read_csv(f"{output}_results.csv")
  #results_df_headers = list(results_df.columns)
